name: My First CI CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run Application locally
      run: node app.js

    # --- INDHA PUDHU DOCKER STEP INGA UTKARA NUM ---
    - name: Build Docker Image
      run: |
        docker build -t my-devops-app:${{ github.sha }} .
        echo "Docker Image Built Successfully!"